# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transinfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='transinfo.proto',
  package='transinfo',
  syntax='proto3',
  serialized_options=b'\n\032io.grpc.examples.transinfoB\016TransInfoProtoP\001\242\002\003TIP',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ftransinfo.proto\x12\ttransinfo\"\x1b\n\x0bInfoSending\x12\x0c\n\x04info\x18\x01 \x01(\t\"\x1d\n\x0cSuccessReply\x12\r\n\x05reply\x18\x01 \x01(\x03\x32I\n\tTransInfo\x12<\n\x07GetInfo\x12\x16.transinfo.InfoSending\x1a\x17.transinfo.SuccessReply\"\x00\x42\x34\n\x1aio.grpc.examples.transinfoB\x0eTransInfoProtoP\x01\xa2\x02\x03TIPb\x06proto3'
)




_INFOSENDING = _descriptor.Descriptor(
  name='InfoSending',
  full_name='transinfo.InfoSending',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='transinfo.InfoSending.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=57,
)


_SUCCESSREPLY = _descriptor.Descriptor(
  name='SuccessReply',
  full_name='transinfo.SuccessReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='transinfo.SuccessReply.reply', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['InfoSending'] = _INFOSENDING
DESCRIPTOR.message_types_by_name['SuccessReply'] = _SUCCESSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InfoSending = _reflection.GeneratedProtocolMessageType('InfoSending', (_message.Message,), {
  'DESCRIPTOR' : _INFOSENDING,
  '__module__' : 'transinfo_pb2'
  # @@protoc_insertion_point(class_scope:transinfo.InfoSending)
  })
_sym_db.RegisterMessage(InfoSending)

SuccessReply = _reflection.GeneratedProtocolMessageType('SuccessReply', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESSREPLY,
  '__module__' : 'transinfo_pb2'
  # @@protoc_insertion_point(class_scope:transinfo.SuccessReply)
  })
_sym_db.RegisterMessage(SuccessReply)


DESCRIPTOR._options = None

_TRANSINFO = _descriptor.ServiceDescriptor(
  name='TransInfo',
  full_name='transinfo.TransInfo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=90,
  serialized_end=163,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetInfo',
    full_name='transinfo.TransInfo.GetInfo',
    index=0,
    containing_service=None,
    input_type=_INFOSENDING,
    output_type=_SUCCESSREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSINFO)

DESCRIPTOR.services_by_name['TransInfo'] = _TRANSINFO

# @@protoc_insertion_point(module_scope)
